name: MLOps CI

on:
  push:
    branches:
      - main

jobs:
  verify-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Verify Runner
        run: |
          echo "GitHub Actions is working!"
          python --version

      - name: Run Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests
        run: |
          export PYTHONPATH=$PWD
          python -m pytest